### ISSUE TITLE
main__content内のa要素

### ISSUE THREAD

**Issue by bonprosoft** [bonprosoft/MSPJPWebSite#13]
text-decoration:noneになっていますが、main__contentの内部は欲しいですかね（というのも、どこがリンクかわからないです

**Comment by katsumitakano** [comment]
main__content以下のaタグは`#19568e`の色にしました。
ブログ一覧やタグの中の色まで変わってますが、デザイン的にどうでしょう？

**Comment by bonprosoft** [comment]
失礼、.entry_bodyにしましょう
修正しておきます

**Comment by katsumitakano** [comment]
どうもですm(_ _)m
