### ISSUE TITLE
aboutとcontactページのデザイン

### ISSUE THREAD

**Issue by damjing** [bonprosoft/MSPJPWebSite#16]
サイドバーは不要だと思われるのでMSPJPWPThemeの方では消してあります。
すると横幅が画面に対して狭くなるので、
・他のページに合わせてそのままにしておく
・画面に合わせて広げる
という選択肢がありますが、どっちがいいでしょうか
(個人的には、右下に背景の絵がくるので広げないでこのままでも綺麗かと思いました)

**Comment by katsumitakano** [comment]
僕も画面に合わせて広げる必要はないと思います。
aboutとcontactだけhtmlの構造変えるのも面倒ですし。

**Comment by bonprosoft** [comment]
まあ解決策としてmain__contentに何かクラスを付けて、widthを書き換えとかもありですが、現状はこれで！
