### ISSUE TITLE
singleページのHTML確定

### ISSUE THREAD

**Issue by bonprosoft** [bonprosoft/MSPJPWebSite#2]
決まったら閉じてください。

**Comment by katsumitakano** [comment]
![single](https://cloud.githubusercontent.com/assets/3479375/6317427/3822e4c6-ba95-11e4-8178-2485c02a9c46.png)

**Comment by katsumitakano** [comment]
HTMLはOK
CSSはちゃんと調整する必要あり

**Comment by bonprosoft** [comment]
対応しました
https://github.com/bonprosoft/MSPJPWPTheme/commit/04b71580b9795971c6922a088b79f48f9acd0bfd
