### ISSUE TITLE
indexのHTML確定

### ISSUE THREAD

**Issue by bonprosoft** [bonprosoft/MSPJPWebSite#4]
決まったら閉じてください。

**Comment by bonprosoft** [comment]
headerもここで決定

**Comment by hunzy** [comment]
![top](https://cloud.githubusercontent.com/assets/3479375/6317414/ade90222-ba94-11e4-89d2-0ae204d4331d.png)

**Comment by katsumitakano** [comment]
![index](https://cloud.githubusercontent.com/assets/3479375/6317425/00407226-ba95-11e4-9046-2fc39127a04f.jpg)

**Comment by katsumitakano** [comment]
HTMLの構造はOK
CSSも多少変更しました（軽くレスポンシブ対応）

**Comment by bonprosoft** [comment]
素晴らしいです

**Comment by bonprosoft** [comment]
対応完了
https://github.com/bonprosoft/MSPJPWPTheme/commit/f98cefc1dfd26c7efee00aa298141f8cfbd51da2

**Comment by bonprosoft** [comment]
スライダはまだ実装されてないですよね？

**Comment by katsumitakano** [comment]
## スライダ実装

画像の説明文
- Title
- 日付
- 説明文

画像全体にリンクを付ける

**Comment by katsumitakano** [comment]
スライドをクリック出来るようにした
下部に説明文を追加
デザインは適当

**Comment by bonprosoft** [comment]
対応しました
https://github.com/bonprosoft/MSPJPWPTheme/commit/321007dc8b1d8891e584c51a11b3225f6c5a25cf
https://github.com/bonprosoft/MSPJPWPTheme/commit/fc428b2a03ecfb3e35a841e49e90b0edf592e2b3
https://github.com/bonprosoft/MSPJPWPTheme/commit/c28f6d423f5f60d6f6c2a22f16905823908dd69b
