### ISSUE TITLE
blog(アーカイブ)のHTMLの確定

### ISSUE THREAD

**Issue by bonprosoft** [bonprosoft/MSPJPWebSite#5]
決まったら閉じて

**Comment by katsumitakano** [comment]
![blog](https://cloud.githubusercontent.com/assets/3479375/6317405/91cebadc-ba94-11e4-9c31-b55adfe6780a.png)

**Comment by katsumitakano** [comment]
見出し，記事一覧のHTMLはOK
CSSかなりリファクタリングした
サイドバー内のコンテンツは何も書いてないけど、多分Wordpressのウィジェットそのまま入れれば良いと思う。

**Comment by bonprosoft** [comment]
対応完了
https://github.com/bonprosoft/MSPJPWPTheme/commit/0d4b3cb52b78c5fb5b72f7ebba6cde0877f76e69
