### ISSUE TITLE
Profileの詳細ページのHTMLを確定

### ISSUE THREAD

**Issue by bonprosoft** [bonprosoft/MSPJPWebSite#6]
必要な内容
- 名前（いつものh1）
- 顔写真
- 所属チーム（複数あり、プロジェクトへのリンク付き）
- 所属年度(2013,2014など、リンク付き)
- WordPressのユーザー名（リンクを付けて、そのユーザーが投稿した一覧を表示するように設定する）
- 自己紹介文
- 関連する投稿（「xxxを開催しました」などの投稿と関連付ける。かなり多いので自己紹介の後に列挙）

ほか何かあったらコメントください。

**Comment by katsumitakano** [comment]
ファイル名はprofile-detail.html
大元のクラス名はprofilepage

名前：profilepage__name
顔写真：profilepage__image
所属チーム：profilepage__projects
所属年度：profilepage__year
ユーザ名：profilepage__username
自己紹介文：profilepage__introduce
関連する投稿：postをそのまま使う

**Comment by katsumitakano** [comment]
出来てる
