### ISSUE TITLE
タイポグラフィ

### ISSUE THREAD

**Issue by bonprosoft** [bonprosoft/MSPJPWebSite#8]
@Mizune さんお願いします

**Comment by bonprosoft** [comment]
/blog/50 などにアタッチメントデータのある記事を投稿しました。
WPのSnippetが吐き出すclassに対してcssをお願いします。

**Comment by bonprosoft** [comment]
こちら、どなたか進めていただけませんか @Mizune

**Comment by Mizune** [comment]
singleに対していくつか打った気がするのですが・・・　wp側をいじる感じですか？

**Comment by bonprosoft** [comment]
[staging]/blog/50
のキャプションテスト（アタッチメントページへのリンク付き, WP Snippet）とかにcssとかってつけてますか？
